<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pathly Data\Pathly Data.csproj" />
    <ProjectReference Include="..\Pathly_Interfaces\Pathly_Interfaces.csproj" />
  </ItemGroup>

</Project>
