// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pathly_Data;

#nullable disable

namespace Pathly_Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260830152335_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.AcademicRecords", b =>
                {
                    b.Property<Guid>("AcadmicRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClalculatedAPS")
                        .HasColumnType("integer");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.Property<string>("StudentName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AcadmicRecordId");

                    b.ToTable("AcademicRecords");
                });

            modelBuilder.Entity("Pathly_Models.AiResponse", b =>
                {
                    b.Property<Guid>("AiResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicPersonality")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnalysisVersion")
                        .HasColumnType("text");

                    b.Property<Guid>("ApsAnalysisId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("BursariesAvailable")
                        .HasColumnType("text[]");

                    b.Property<string>("FeedBack")
                        .HasColumnType("text");

                    b.Property<string>("FiveYearsOutLook")
                        .HasColumnType("text");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<string>("ImprovementtoRoadmap")
                        .HasColumnType("text");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<string>("MotivationalMessage")
                        .HasColumnType("text");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<string>("ParentSummary")
                        .HasColumnType("text");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("text");

                    b.Property<string>("PsychometricHash")
                        .HasColumnType("text");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("text");

                    b.Property<string>("RiskAssessment")
                        .HasColumnType("text");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("SkillsToLearn")
                        .HasColumnType("text[]");

                    b.Property<string>("StudyTips")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("SubjectChangeSuggestion")
                        .HasColumnType("text[]");

                    b.Property<string>("SubjectSetHash")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("TeacherRecommendation")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("UniversitiestoConsider")
                        .HasColumnType("text[]");

                    b.Property<string>("UserFullName")
                        .HasColumnType("text");

                    b.Property<string>("UserStrength")
                        .HasColumnType("text");

                    b.Property<string>("UserWeaknesses")
                        .HasColumnType("text");

                    b.HasKey("AiResponseId");

                    b.HasIndex("ApsAnalysisId");

                    b.ToTable("AiResponse");
                });

            modelBuilder.Entity("Pathly_Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MicrosoftId")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProofilePictures")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Subscription")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.ApsAnalysis", b =>
                {
                    b.Property<Guid>("ApsAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApsExplanation")
                        .HasColumnType("text");

                    b.Property<int>("CalculatedAps")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImprovementAdviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImprovementId")
                        .HasColumnType("uuid");

                    b.Property<string>("QualificationMessage")
                        .HasColumnType("text");

                    b.Property<bool>("QualifiesForUniversity")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("UniversitiesTheyQualifyFor")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("UniversitiestheyDoNotQualifyFor")
                        .HasColumnType("text[]");

                    b.HasKey("ApsAnalysisId");

                    b.HasIndex("ImprovementAdviceId");

                    b.ToTable("ApsAnalysiss");
                });

            modelBuilder.Entity("Pathly_Models.CareerMatch", b =>
                {
                    b.Property<Guid>("CareerMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AiResponseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Field")
                        .HasColumnType("text");

                    b.Property<string>("JobDescription")
                        .HasColumnType("text");

                    b.Property<int>("MatchPercentage")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("text");

                    b.Property<string>("TimeToQualify")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("TopCompaniesHiring")
                        .HasColumnType("text[]");

                    b.Property<string>("UniversityCourse")
                        .HasColumnType("text");

                    b.Property<string>("growthPotentials")
                        .HasColumnType("text");

                    b.Property<string>("requiredSubjects")
                        .HasColumnType("text");

                    b.HasKey("CareerMatchId");

                    b.HasIndex("AiResponseId");

                    b.ToTable("CareerMaths");
                });

            modelBuilder.Entity("Pathly_Models.CareerProfile", b =>
                {
                    b.Property<Guid>("CareerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArtisticWeight")
                        .HasColumnType("integer");

                    b.Property<string>("CareerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ConventionalWeight")
                        .HasColumnType("integer");

                    b.Property<int>("DemandScore")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EnterprisingWeight")
                        .HasColumnType("integer");

                    b.Property<int>("GrowthScore")
                        .HasColumnType("integer");

                    b.Property<int>("InvestigativeWeight")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumAps")
                        .HasColumnType("integer");

                    b.Property<int>("RealisticWeight")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredSubjects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SocialWeight")
                        .HasColumnType("integer");

                    b.HasKey("CareerProfileId");

                    b.ToTable("CareerProfiles");
                });

            modelBuilder.Entity("Pathly_Models.CreditTransaction", b =>
                {
                    b.Property<Guid>("CreditTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CreditTransactionId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("Pathly_Models.DemandingCareerAssessment", b =>
                {
                    b.Property<Guid>("DemandingCareerAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AiResponseId")
                        .HasColumnType("uuid");

                    b.Property<string>("AlternativeRoute")
                        .HasColumnType("text");

                    b.Property<bool>("CanStudentQualify")
                        .HasColumnType("boolean");

                    b.Property<string>("CareerTitle")
                        .HasColumnType("text");

                    b.Property<int>("ChancesifTheyOpt")
                        .HasColumnType("integer");

                    b.Property<string>("GlobalDemandLevel")
                        .HasColumnType("text");

                    b.Property<string>("HonestyMessage")
                        .HasColumnType("text");

                    b.Property<string>("QualificationVerdict")
                        .HasColumnType("text");

                    b.Property<string>("ReasonForVerdict")
                        .HasColumnType("text");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("SubjectsTheyAreMissing")
                        .HasColumnType("text[]");

                    b.Property<string>("WhatTheyNeedToSuccess")
                        .HasColumnType("text");

                    b.Property<string>("WhyitIsInDemand")
                        .HasColumnType("text");

                    b.HasKey("DemandingCareerAssessmentId");

                    b.HasIndex("AiResponseId");

                    b.ToTable("DemandingCareerAssessments");
                });

            modelBuilder.Entity("Pathly_Models.DyingCareerWarning", b =>
                {
                    b.Property<Guid>("DyingCareerWarningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AiResponseId")
                        .HasColumnType("uuid");

                    b.Property<string>("BetterAlternative")
                        .HasColumnType("text");

                    b.Property<string>("CareerTitle")
                        .HasColumnType("text");

                    b.Property<int>("ChanceOfGettingJobAfterStudying")
                        .HasColumnType("integer");

                    b.Property<string>("Honestwarning")
                        .HasColumnType("text");

                    b.Property<bool>("IsRelevanttoStudent")
                        .HasColumnType("boolean");

                    b.Property<int>("JobAvailabilityIn5Years")
                        .HasColumnType("integer");

                    b.Property<string>("MotivationalRedirect")
                        .HasColumnType("text");

                    b.Property<string>("RelevanceReason")
                        .HasColumnType("text");

                    b.Property<string>("WhyItIsDying")
                        .HasColumnType("text");

                    b.HasKey("DyingCareerWarningId");

                    b.HasIndex("AiResponseId");

                    b.ToTable("DyingCareerWarning");
                });

            modelBuilder.Entity("Pathly_Models.EmploymentOutlook", b =>
                {
                    b.Property<Guid>("EmploymentOutlookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AiResponseId")
                        .HasColumnType("uuid");

                    b.Property<string>("AverageTimeToGetFirstJob")
                        .HasColumnType("text");

                    b.Property<string>("CareerTitle")
                        .HasColumnType("text");

                    b.Property<int>("ChanceOfEmploymentAfterGraduation")
                        .HasColumnType("integer");

                    b.Property<string>("EntryLevelSalary")
                        .HasColumnType("text");

                    b.Property<string>("GlobalOpportunities")
                        .HasColumnType("text");

                    b.Property<string>("JobMarketCompetition")
                        .HasColumnType("text");

                    b.Property<string>("OutlookSummry")
                        .HasColumnType("text");

                    b.Property<string>("SeniorLevelSalary")
                        .HasColumnType("text");

                    b.Property<string>("SouthAfricanMarketInsight")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("TopIndustriesHiring")
                        .HasColumnType("text[]");

                    b.HasKey("EmploymentOutlookId");

                    b.HasIndex("AiResponseId");

                    b.ToTable("EmploymentOutlooks");
                });

            modelBuilder.Entity("Pathly_Models.ExtractedAcademicRecord", b =>
                {
                    b.Property<Guid>("ExtractionAcademicRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("text");

                    b.Property<string>("InstitutionType")
                        .HasColumnType("text");

                    b.Property<string>("RawExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("StudentName")
                        .HasColumnType("text");

                    b.Property<string>("StudyLevel")
                        .HasColumnType("text");

                    b.HasKey("ExtractionAcademicRecordId");

                    b.ToTable("ExtractedAcademicRecords");
                });

            modelBuilder.Entity("Pathly_Models.ExtractedSubject", b =>
                {
                    b.Property<Guid>("ExtractionSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExtractedAcademicRecordExtractionAcademicRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarkType")
                        .HasColumnType("text");

                    b.Property<int?>("NumericMark")
                        .HasColumnType("integer");

                    b.Property<string>("RawMark")
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.HasKey("ExtractionSubjectId");

                    b.HasIndex("ExtractedAcademicRecordExtractionAcademicRecordId");

                    b.ToTable("ExtractedSubjects");
                });

            modelBuilder.Entity("Pathly_Models.ImprovementAdvice", b =>
                {
                    b.Property<Guid>("ImprovementAdviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("AlternativeOptions")
                        .HasColumnType("text[]");

                    b.Property<string>("MotivationalGuidance")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("RecommendedSubjecrsToImprove")
                        .HasColumnType("text[]");

                    b.Property<bool>("ShouldReWriteMatric")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldUpgradeSubjects")
                        .HasColumnType("boolean");

                    b.HasKey("ImprovementAdviceId");

                    b.ToTable("ImprovementAdvices");
                });

            modelBuilder.Entity("Pathly_Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountInCents")
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderTransactionRef")
                        .HasColumnType("text");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("PlanId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Pathly_Models.Plan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IncludesPremiumAnalysis")
                        .HasColumnType("boolean");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MonthlyAnalysisQuota")
                        .HasColumnType("integer");

                    b.Property<int?>("MonthlyPsychometricQuota")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceInCents")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderPlanCode")
                        .HasColumnType("text");

                    b.HasKey("PlanId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Pathly_Models.PsychometricAssessment", b =>
                {
                    b.Property<Guid>("PsychometricAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnsweredQuestions")
                        .HasColumnType("integer");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MultipleChoiceAnswersJson")
                        .HasColumnType("text");

                    b.Property<Guid>("PsychometricProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RatingAnswersJson")
                        .HasColumnType("text");

                    b.Property<string>("ResultFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<string>("TrueFalseAnswersJson")
                        .HasColumnType("text");

                    b.HasKey("PsychometricAssessmentId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("PsychometricProfileId");

                    b.ToTable("PsychometricAssessments");
                });

            modelBuilder.Entity("Pathly_Models.PsychometricProfile", b =>
                {
                    b.Property<Guid>("PsychometricProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<int>("Artistic")
                        .HasColumnType("integer");

                    b.Property<int>("Conventional")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Enterprising")
                        .HasColumnType("integer");

                    b.Property<int>("Investigative")
                        .HasColumnType("integer");

                    b.Property<int>("Realistic")
                        .HasColumnType("integer");

                    b.Property<int>("Social")
                        .HasColumnType("integer");

                    b.HasKey("PsychometricProfileId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("PsychometricProfiles");
                });

            modelBuilder.Entity("Pathly_Models.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Pathly_Models.SubjectResults", b =>
                {
                    b.Property<Guid>("SubjectResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AiResponseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CareerRelevance")
                        .HasColumnType("text");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<string>("ImprovementTip")
                        .HasColumnType("text");

                    b.Property<int>("Mark")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("SubjectResultId");

                    b.HasIndex("AcademicRecordId");

                    b.HasIndex("AiResponseId");

                    b.ToTable("SubjectResults");
                });

            modelBuilder.Entity("Pathly_Models.UniveristyQualification", b =>
                {
                    b.Property<Guid>("UnviversityQualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gap")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumAPS")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("RecommendedCourse")
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("UnviversityQualificationId");

                    b.ToTable("UniveristyQualifications");
                });

            modelBuilder.Entity("Pathly_Models.UsageTransaction", b =>
                {
                    b.Property<Guid>("UsageTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstimatedCostInCents")
                        .HasColumnType("integer");

                    b.Property<int>("Units")
                        .HasColumnType("integer");

                    b.Property<int>("UsageType")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsageTransactionId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("UsageTransactions");
                });

            modelBuilder.Entity("Pathly_Models.UserSubscription", b =>
                {
                    b.Property<Guid>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CurrentPeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderSubscriptionRef")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserSubscriptionId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly_Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathly_Models.AiResponse", b =>
                {
                    b.HasOne("Pathly_Models.ApsAnalysis", "ApsAnalysis")
                        .WithMany()
                        .HasForeignKey("ApsAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApsAnalysis");
                });

            modelBuilder.Entity("Pathly_Models.ApsAnalysis", b =>
                {
                    b.HasOne("Pathly_Models.ImprovementAdvice", "ImprovementAdvice")
                        .WithMany()
                        .HasForeignKey("ImprovementAdviceId");

                    b.Navigation("ImprovementAdvice");
                });

            modelBuilder.Entity("Pathly_Models.CareerMatch", b =>
                {
                    b.HasOne("Pathly_Models.AiResponse", null)
                        .WithMany("Top5BestCareers")
                        .HasForeignKey("AiResponseId");
                });

            modelBuilder.Entity("Pathly_Models.CreditTransaction", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Pathly_Models.DemandingCareerAssessment", b =>
                {
                    b.HasOne("Pathly_Models.AiResponse", null)
                        .WithMany("DemandingCareers")
                        .HasForeignKey("AiResponseId");
                });

            modelBuilder.Entity("Pathly_Models.DyingCareerWarning", b =>
                {
                    b.HasOne("Pathly_Models.AiResponse", null)
                        .WithMany("DyingCareerWarnings")
                        .HasForeignKey("AiResponseId");
                });

            modelBuilder.Entity("Pathly_Models.EmploymentOutlook", b =>
                {
                    b.HasOne("Pathly_Models.AiResponse", null)
                        .WithMany("EmploymentOutlooks")
                        .HasForeignKey("AiResponseId");
                });

            modelBuilder.Entity("Pathly_Models.ExtractedSubject", b =>
                {
                    b.HasOne("Pathly_Models.ExtractedAcademicRecord", null)
                        .WithMany("Subjects")
                        .HasForeignKey("ExtractedAcademicRecordExtractionAcademicRecordId");
                });

            modelBuilder.Entity("Pathly_Models.PaymentTransaction", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Pathly_Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Pathly_Models.PsychometricAssessment", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly_Models.PsychometricProfile", "PsychometricProfile")
                        .WithMany()
                        .HasForeignKey("PsychometricProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("PsychometricProfile");
                });

            modelBuilder.Entity("Pathly_Models.PsychometricProfile", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Pathly_Models.SubjectResults", b =>
                {
                    b.HasOne("Pathly_Models.AcademicRecords", "AcademicRecord")
                        .WithMany("SubjectResults")
                        .HasForeignKey("AcademicRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly_Models.AiResponse", null)
                        .WithMany("SubjectResults")
                        .HasForeignKey("AiResponseId");

                    b.Navigation("AcademicRecord");
                });

            modelBuilder.Entity("Pathly_Models.UsageTransaction", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Pathly_Models.UserSubscription", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Pathly_Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Pathly_Models.AcademicRecords", b =>
                {
                    b.Navigation("SubjectResults");
                });

            modelBuilder.Entity("Pathly_Models.AiResponse", b =>
                {
                    b.Navigation("DemandingCareers");

                    b.Navigation("DyingCareerWarnings");

                    b.Navigation("EmploymentOutlooks");

                    b.Navigation("SubjectResults");

                    b.Navigation("Top5BestCareers");
                });

            modelBuilder.Entity("Pathly_Models.ExtractedAcademicRecord", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
