// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pathly_Data;

#nullable disable

namespace Pathly_Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.AcademicRecords", b =>
                {
                    b.Property<Guid>("AcadmicRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClalculatedAPS")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AcadmicRecordId");

                    b.ToTable("AcademicRecords", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.AiResponse", b =>
                {
                    b.Property<Guid>("AiResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicPersonality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnalysisVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ApsAnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("BursariesAvailable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiveYearsOutLook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImprovementtoRoadmap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("MotivationalMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<string>("ParentSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PsychometricHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SkillsToLearn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyTips")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SubjectChangeSuggestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectSetHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherRecommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("UniversitiestoConsider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserWeaknesses")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AiResponseId");

                    b.HasIndex("ApsAnalysisId");

                    b.ToTable("AiResponse", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MicrosoftId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProofilePictures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subscription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.ApsAnalysis", b =>
                {
                    b.Property<Guid>("ApsAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApsExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CalculatedAps")
                        .HasColumnType("int");

                    b.Property<Guid?>("ImprovementAdviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImprovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QualificationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QualifiesForUniversity")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("UniversitiesTheyQualifyFor")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("UniversitiestheyDoNotQualifyFor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApsAnalysisId");

                    b.HasIndex("ImprovementAdviceId");

                    b.ToTable("ApsAnalysiss", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.CareerMatch", b =>
                {
                    b.Property<Guid>("CareerMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AiResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeToQualify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("TopCompaniesHiring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityCourse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("growthPotentials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requiredSubjects")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CareerMatchId");

                    b.HasIndex("AiResponseId");

                    b.ToTable("CareerMaths", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.CareerProfile", b =>
                {
                    b.Property<Guid>("CareerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArtisticWeight")
                        .HasColumnType("int");

                    b.Property<string>("CareerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConventionalWeight")
                        .HasColumnType("int");

                    b.Property<int>("DemandScore")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnterprisingWeight")
                        .HasColumnType("int");

                    b.Property<int>("GrowthScore")
                        .HasColumnType("int");

                    b.Property<int>("InvestigativeWeight")
                        .HasColumnType("int");

                    b.Property<int>("MinimumAps")
                        .HasColumnType("int");

                    b.Property<int>("RealisticWeight")
                        .HasColumnType("int");

                    b.Property<string>("RequiredSubjects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SocialWeight")
                        .HasColumnType("int");

                    b.HasKey("CareerProfileId");

                    b.ToTable("CareerProfiles", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.CreditTransaction", b =>
                {
                    b.Property<Guid>("CreditTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Delta")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CreditTransactionId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditTransactions", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.DemandingCareerAssessment", b =>
                {
                    b.Property<Guid>("DemandingCareerAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AiResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternativeRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanStudentQualify")
                        .HasColumnType("bit");

                    b.Property<string>("CareerTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChancesifTheyOpt")
                        .HasColumnType("int");

                    b.Property<string>("GlobalDemandLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HonestyMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualificationVerdict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForVerdict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SubjectsTheyAreMissing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatTheyNeedToSuccess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhyitIsInDemand")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DemandingCareerAssessmentId");

                    b.HasIndex("AiResponseId");

                    b.ToTable("DemandingCareerAssessments", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.DyingCareerWarning", b =>
                {
                    b.Property<Guid>("DyingCareerWarningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AiResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BetterAlternative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CareerTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChanceOfGettingJobAfterStudying")
                        .HasColumnType("int");

                    b.Property<string>("Honestwarning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRelevanttoStudent")
                        .HasColumnType("bit");

                    b.Property<int>("JobAvailabilityIn5Years")
                        .HasColumnType("int");

                    b.Property<string>("MotivationalRedirect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelevanceReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhyItIsDying")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DyingCareerWarningId");

                    b.HasIndex("AiResponseId");

                    b.ToTable("DyingCareerWarning", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.EmploymentOutlook", b =>
                {
                    b.Property<Guid>("EmploymentOutlookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AiResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AverageTimeToGetFirstJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CareerTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChanceOfEmploymentAfterGraduation")
                        .HasColumnType("int");

                    b.Property<string>("EntryLevelSalary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalOpportunities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobMarketCompetition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutlookSummry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeniorLevelSalary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SouthAfricanMarketInsight")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("TopIndustriesHiring")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmploymentOutlookId");

                    b.HasIndex("AiResponseId");

                    b.ToTable("EmploymentOutlooks", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.ExtractedAcademicRecord", b =>
                {
                    b.Property<Guid>("ExtractionAcademicRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExtractionAcademicRecordId");

                    b.ToTable("ExtractedAcademicRecords", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.ExtractedSubject", b =>
                {
                    b.Property<Guid>("ExtractionSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExtractedAcademicRecordExtractionAcademicRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MarkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumericMark")
                        .HasColumnType("int");

                    b.Property<string>("RawMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExtractionSubjectId");

                    b.HasIndex("ExtractedAcademicRecordExtractionAcademicRecordId");

                    b.ToTable("ExtractedSubjects", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.ImprovementAdvice", b =>
                {
                    b.Property<Guid>("ImprovementAdviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("AlternativeOptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivationalGuidance")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("RecommendedSubjecrsToImprove")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShouldReWriteMatric")
                        .HasColumnType("bit");

                    b.Property<bool>("ShouldUpgradeSubjects")
                        .HasColumnType("bit");

                    b.HasKey("ImprovementAdviceId");

                    b.ToTable("ImprovementAdvices", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountInCents")
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderTransactionRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("PlanId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.Plan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Audience")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IncludesPremiumAnalysis")
                        .HasColumnType("bit");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MonthlyAnalysisQuota")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyPsychometricQuota")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceInCents")
                        .HasColumnType("int");

                    b.Property<string>("ProviderPlanCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.PsychometricAssessment", b =>
                {
                    b.Property<Guid>("PsychometricAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnsweredQuestions")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MultipleChoiceAnswersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PsychometricProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RatingAnswersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultFingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("TrueFalseAnswersJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PsychometricAssessmentId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("PsychometricProfileId");

                    b.ToTable("PsychometricAssessments", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.PsychometricProfile", b =>
                {
                    b.Property<Guid>("PsychometricProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Artistic")
                        .HasColumnType("int");

                    b.Property<int>("Conventional")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Enterprising")
                        .HasColumnType("int");

                    b.Property<int>("Investigative")
                        .HasColumnType("int");

                    b.Property<int>("Realistic")
                        .HasColumnType("int");

                    b.Property<int>("Social")
                        .HasColumnType("int");

                    b.HasKey("PsychometricProfileId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("PsychometricProfiles", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.SubjectResults", b =>
                {
                    b.Property<Guid>("SubjectResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AiResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CareerRelevance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImprovementTip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectResultId");

                    b.HasIndex("AcademicRecordId");

                    b.HasIndex("AiResponseId");

                    b.ToTable("SubjectResults", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.UniveristyQualification", b =>
                {
                    b.Property<Guid>("UnviversityQualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gap")
                        .HasColumnType("int");

                    b.Property<int>("MinimumAPS")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("RecommendedCourse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnviversityQualificationId");

                    b.ToTable("UniveristyQualifications", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.UsageTransaction", b =>
                {
                    b.Property<Guid>("UsageTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstimatedCostInCents")
                        .HasColumnType("int");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.Property<int>("UsageType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UsageTransactionId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("UsageTransactions", (string)null);
                });

            modelBuilder.Entity("Pathly_Models.UserSubscription", b =>
                {
                    b.Property<Guid>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CurrentPeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderSubscriptionRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserSubscriptionId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("UserSubscriptions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly_Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathly_Models.AiResponse", b =>
                {
                    b.HasOne("Pathly_Models.ApsAnalysis", "ApsAnalysis")
                        .WithMany()
                        .HasForeignKey("ApsAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApsAnalysis");
                });

            modelBuilder.Entity("Pathly_Models.ApsAnalysis", b =>
                {
                    b.HasOne("Pathly_Models.ImprovementAdvice", "ImprovementAdvice")
                        .WithMany()
                        .HasForeignKey("ImprovementAdviceId");

                    b.Navigation("ImprovementAdvice");
                });

            modelBuilder.Entity("Pathly_Models.CareerMatch", b =>
                {
                    b.HasOne("Pathly_Models.AiResponse", null)
                        .WithMany("Top5BestCareers")
                        .HasForeignKey("AiResponseId");
                });

            modelBuilder.Entity("Pathly_Models.CreditTransaction", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Pathly_Models.DemandingCareerAssessment", b =>
                {
                    b.HasOne("Pathly_Models.AiResponse", null)
                        .WithMany("DemandingCareers")
                        .HasForeignKey("AiResponseId");
                });

            modelBuilder.Entity("Pathly_Models.DyingCareerWarning", b =>
                {
                    b.HasOne("Pathly_Models.AiResponse", null)
                        .WithMany("DyingCareerWarnings")
                        .HasForeignKey("AiResponseId");
                });

            modelBuilder.Entity("Pathly_Models.EmploymentOutlook", b =>
                {
                    b.HasOne("Pathly_Models.AiResponse", null)
                        .WithMany("EmploymentOutlooks")
                        .HasForeignKey("AiResponseId");
                });

            modelBuilder.Entity("Pathly_Models.ExtractedSubject", b =>
                {
                    b.HasOne("Pathly_Models.ExtractedAcademicRecord", null)
                        .WithMany("Subjects")
                        .HasForeignKey("ExtractedAcademicRecordExtractionAcademicRecordId");
                });

            modelBuilder.Entity("Pathly_Models.PaymentTransaction", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Pathly_Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Pathly_Models.PsychometricAssessment", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly_Models.PsychometricProfile", "PsychometricProfile")
                        .WithMany()
                        .HasForeignKey("PsychometricProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("PsychometricProfile");
                });

            modelBuilder.Entity("Pathly_Models.PsychometricProfile", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Pathly_Models.SubjectResults", b =>
                {
                    b.HasOne("Pathly_Models.AcademicRecords", "AcademicRecord")
                        .WithMany("SubjectResults")
                        .HasForeignKey("AcademicRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pathly_Models.AiResponse", null)
                        .WithMany("SubjectResults")
                        .HasForeignKey("AiResponseId");

                    b.Navigation("AcademicRecord");
                });

            modelBuilder.Entity("Pathly_Models.UsageTransaction", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Pathly_Models.UserSubscription", b =>
                {
                    b.HasOne("Pathly_Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Pathly_Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Pathly_Models.AcademicRecords", b =>
                {
                    b.Navigation("SubjectResults");
                });

            modelBuilder.Entity("Pathly_Models.AiResponse", b =>
                {
                    b.Navigation("DemandingCareers");

                    b.Navigation("DyingCareerWarnings");

                    b.Navigation("EmploymentOutlooks");

                    b.Navigation("SubjectResults");

                    b.Navigation("Top5BestCareers");
                });

            modelBuilder.Entity("Pathly_Models.ExtractedAcademicRecord", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
