<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Pathly_Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pathly DTOs\Pathly DTOs.csproj" />
    <ProjectReference Include="..\Pathly Helper\Pathly Helper.csproj" />
    <ProjectReference Include="..\Pathly Services\Pathly Services.csproj" />
    <ProjectReference Include="..\PathlyInterfaces\PathlyInterfaces.csproj" />
  </ItemGroup>

</Project>
